name: watchapp_flutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  image_picker: "^0.1.1"
  qrcode_reader: "^0.3.2"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/testIcon.jpg
  - images/icon_about_us.png
  - images/icon_famliy.png
  - images/icon_lock.png
  - images/icon_message.png
  - images/icon_phone.png
  - images/icon_watch.png
  - images/btn_next2_n.png
  - images/btn_code.png
  - images/icon_bloodpressure.png
  - images/icon_heart.png
  - images/icon_temperature.png
  - images/btn_add.png
  - images/btn_machine_n.png
  - images/btn_machine_s.png
  - images/btn_switch_bg1.png
  - images/btn_switch_bg2.png
  - images/btn_switch.png
  - images/icon_bedroom.png
  - images/icon_home2_n.png
  - images/icon_home2_s.png
  - images/icon_kitchen.png
  - images/icon_livingroom.png
  - images/icon_outhome_n.png
  - images/icon_outhome_s.png
  - images/icon_sleep_n.png
  - images/icon_sleep_s.png
  - images/icon_study.png
  - images/icon_wakeup_n.png
  - images/icon_wakeup_s.png
  - images/btn_back.png
  - images/btn_m_d.png
  - images/btn_m_n.png
  - images/btn_m_s.png
  - images/btn_s_d.png
  - images/btn_s_n.png
  - images/btn_s_s.png
  - images/btn_round1.png
  - images/btn_round2.png
  - images/img_clock.png
  - images/icon_phone_gold.png
  - images/icon_canmera.png
  - images/icon_centercontrol.png
  - images/icon_doorbell.png
  - images/icon_inductor.png
  - images/icon_light.png
  - images/btm_green.png
  - images/btn_blue.png
  - images/btn_morecolor.png
  - images/btn_purple.png
  - images/btn_switch_n.png
  - images/btn_switch_s.png
  - images/btn_yellow.png
  - images/img_down.png
  - images/img_light2.png
  - images/img_switch.png
  - images/img_window.png
  - images/imglight1.png
  - images/moon.png
  - images/sun.png
  - images/img_light_round.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
